# Generated by Django 3.1.5 on 2021-01-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_nm', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('source', models.FileField(upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date_published')),
            ],
        ),
    ]
