# Generated by Django 3.1.5 on 2021-02-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_scrapy_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapy_switch',
            name='switch',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True),
        ),
    ]
